(() => {
 'use strict';
 const params=new URLSearchParams(location.search);
 let language=params.get('lang');
 if(!language){try{language=localStorage.getItem('victoriaLanguage');}catch{}}
 const zh=language?.startsWith('zh');document.documentElement.lang=zh?'zh-HK':'en';
 const t=(en,cn)=>zh?cn:en;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n);
 const translate=(key,fallback)=>zh&&typeof translations!=='undefined'?translations['zh-HK']?.[key]||fallback:fallback;
 window.getProductName=name=>translate('product-'+name,name);
 const select=document.getElementById('productLanguage');select.value=zh?'zh-HK':'en';
 select.onchange=()=>{const url=new URL(location.href);url.searchParams.set('lang',select.value);try{localStorage.setItem('victoriaLanguage',select.value);localStorage.setItem('vd-lang',select.value);}catch{}location.replace(url.href);};
 document.getElementById('browse').textContent=t('Collections','系列');document.getElementById('appointment').textContent=t('Book appointment ↗','預約諮詢 ↗');
 document.querySelector('.skip').textContent=t('Skip to ordering','跳至訂購');
 document.getElementById('careLink').textContent=t('Jewelry Care ↗','珠寶保養 ↗');document.getElementById('termsLink').textContent=t('Terms & Conditions ↗','條款及細則 ↗');document.getElementById('termsLink').href=zh?'T&C-zh-HK.pdf':'T&C.pdf';document.getElementById('privacyLink').textContent=t('Privacy','私隱政策');
 const p=window.VDProducts.products.find(p=>p.id===params.get('item')),main=document.getElementById('productMain');
 if(!p){document.title=t('Piece not found','找不到作品')+' | Victoria Diamonds';main.innerHTML=`<div class="error-page"><h1>${t('Let’s find your piece.','尋找您的珠寶作品。')}</h1><p>${t('This piece could not be found. Explore the collections to continue.','找不到此作品，請瀏覽系列繼續探索。')}</p><a href="view-catalogue.html">${t('Browse all pieces →','瀏覽所有作品 →')}</a></div>`;const meta=document.createElement('meta');meta.name='robots';meta.content='noindex';document.head.append(meta);return;}
 const name=getProductName(p.name),collection=VDProducts.collections[p.collection];
 const categoryNames={Ring:'戒指',Earring:'耳環','Earring Stud':'耳釘',Necklace:'項鏈',Bracelet:'手鏈',Anklet:'腳鏈',Brooch:'胸針',Tiara:'冠冕'};
 document.title=name+' | '+collection[0]+' | Victoria Diamonds';
 document.querySelector('meta[name=description]').content=`${name} — ${collection[0]}. `+t(p.mode==='custom'?'Choose your materials, diamonds and payment option.':'Discover the design and order with Victoria Diamonds.',p.mode==='custom'?'選擇材質、鑽石及付款方式。':'探索設計及訂購詳情。');
 const canonical=document.createElement('link');canonical.rel='canonical';canonical.href='https://victoria-diamonds.com/product.html?item='+encodeURIComponent(p.id);document.head.append(canonical);
 const structured=document.createElement('script');structured.type='application/ld+json';structured.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:p.name,image:'https://victoria-diamonds.com/images/'+encodeURIComponent(p.image),sku:p.id,category:p.category,brand:{'@type':'Brand',name:'Victoria Diamonds'},url:canonical.href});document.head.append(structured);
 const labels={mainSide:t('Main side stones','主要配石'),secondarySide:t('Secondary side stones','次要配石'),finishingSide:t('Finishing stones','點綴鑽石'),centreStone:t('Centre stone','主石'),sideStone:t('Side stones','配石'),totalKarat:t('Total carat weight','總克拉重量'),eachDiamond:t('Each diamond','每顆鑽石'),diamondPrice:t('Diamond price','鑽石價格'),metalPrice:t('Metal price','金屬價格'),info:t('Details','詳情')};
 const details=(p.details||[]).map(d=>`<dt>${esc(labels[d.key]||translate(d.key,d.key))}</dt><dd>${esc(d.value)}</dd>`).join('');
 const enquiry='https://wa.me/447594442577?text='+encodeURIComponent('Hello Victoria Diamonds, I would like to enquire about '+p.name+' from '+collection[0]+'. '+canonical.href);
 main.innerHTML=`<nav class="breadcrumb" aria-label="${t('Breadcrumb','導覽路徑')}"><a href="view-catalogue.html">${t('Collections','系列')}</a> / <a href="${collection[1]}?lang=${document.documentElement.lang}">${esc(collection[zh?2:0])}</a></nav>
 <div class="product-layout"><div class="gallery"><a href="images/${esc(p.image)}" target="_blank" rel="noopener" aria-label="${esc(t('Open full image of ','開啟完整圖片：')+name)}"><img src="images/${esc(p.image)}" alt="${esc(name)}" fetchpriority="high"></a><p>${t('Select the photograph to view it in full. Original design shown.','點選照片檢視完整圖片。圖片為原始設計。')}</p></div>
 <div><section class="product-intro"><p class="eyebrow">${esc(collection[zh?2:0])} · ${esc(zh?categoryNames[p.category]||p.category:p.category)}</p><h1>${esc(name)}</h1><p>${p.mode==='custom'?t('Make this piece your own. Choose your materials and diamonds below, with a confirmed price before you order.','打造專屬珠寶。於下方選擇材質及鑽石，下單前確認報價。'):p.mode==='silver'?t('Your everyday silver piece, ready to order online.','日常純銀珠寶，可於網上訂購。'):t('A piece to discover with our atelier. Contact us to discuss the design and your requirements.','與我們的工作室一起探索此作品，聯絡我們討論設計與需求。')}</p>${p.mode==='silver'?`<p class="product-price">${money(p.price)} <small>GBP</small></p>`:''}</section>
 <section id="order" aria-label="${t('Order your piece','訂購作品')}" tabindex="-1"><div id="productCheckout" class="daily-checkout inline-checkout"></div></section>
 <a class="order-help" href="${enquiry}" target="_blank" rel="noopener">${t('Need help choosing? Ask us about this piece ↗','需要協助選擇？查詢此作品 ↗')}</a>
 <section class="product-details"><details><summary>${t('Original design details','原始設計詳情')}</summary><dl>${p.metal?`<dt>${t('Metal','材質')}</dt><dd>${esc(p.metal)}</dd>`:''}${details}</dl>${p.mode==='custom'?`<p>${t('These are the catalogue details of the original design. Your configured stone total and price above apply to your custom order; starting selections may differ from the photograph.','以上為原始設計的目錄資料。訂製訂單以您於上方選擇的鑽石總重及價格為準；初始選項可能與圖片不同。')}</p>`:''}</details><details><summary>${t('Ordering & payment','訂購及付款')}</summary><p>${p.mode==='enquiry'?t('Contact the atelier for a personalised quotation before ordering.','訂購前請聯絡工作室索取個人化報價。'):t('Enter your name and email to receive a secure payment link. You will complete payment through the link in your email. Submitting this form does not charge your card.','輸入姓名及電郵以接收安全付款連結，並透過電郵中的連結完成付款。提交此表格不會扣款。')}</p><p>${t('Please confirm sizing and delivery requirements with us. See our','請與我們確認尺寸及配送需求。請參閱')} <a href="${zh?'T&C-zh-HK.pdf':'T&C.pdf'}" target="_blank" rel="noopener">${t('terms and conditions','條款及細則')}</a>.</p></details><details><summary>${t('Caring for your jewellery','珠寶保養')}</summary><p><a href="Jewelry-Care.pdf" target="_blank" rel="noopener">${t('Read our jewellery care guide ↗','閱讀珠寶保養指南 ↗')}</a></p></details></section></div></div>`;
 if(p.mode==='custom'){const price=document.createElement('p');price.className='product-price';price.id='productQuote';price.setAttribute('aria-live','polite');price.textContent=t('Confirming price…','正在確認價格…');document.querySelector('.product-intro').append(price);}
 const host=document.getElementById('productCheckout');
 if(p.mode==='custom'){window.VDCheckout.mount(p.preset);}
 else if(p.mode==='enquiry'){host.innerHTML=`<h2>${t('Available by appointment','僅限預約訂購')}</h2><p>${t('This piece cannot be purchased online. Book an appointment to discuss the design, specifications and price with our atelier.','此作品不提供網上購買。請預約與工作室討論設計、規格及價格。')}</p><a class="enquiry-button" href="https://calendly.com/general-victoria-diamonds/30min?utm_content=${encodeURIComponent(p.id)}" target="_blank" rel="noopener">${t('Book an appointment ↗','預約諮詢 ↗')}</a>`;}
 else{host.innerHTML=`<form id="fixedForm"><fieldset id="fixedControls"><legend>${t('Order your piece','訂購作品')}</legend><p>${t('One order item · Sterling 925 · Full payment','一項訂單商品 · 925 純銀 · 全額付款')}</p><div class="daily-summary"><div><span>${t('Total due','應付總額')}</span><strong>${money(p.price)}</strong></div></div><h3>${t('Your details','聯絡資料')}</h3><div class="daily-fields"><label>${t('Full name','姓名')}<input name="name" autocomplete="name" maxlength="120" required></label><label>${t('Email','電郵')}<input name="email" autocomplete="email" type="email" maxlength="254" required></label></div><p id="fixedStatus" role="status"></p><button class="daily-primary" type="submit">${t('Email my secure payment link','發送安全付款連結至電郵')}</button><p class="daily-note">${t('All payments are in GBP. Submitting this form does not charge your card.','所有付款均以英鎊結算。提交此表格不會扣款。')}</p></fieldset></form>`;
  document.getElementById('fixedForm').addEventListener('submit',async e=>{
   e.preventDefault();const form=e.currentTarget,controls=document.getElementById('fixedControls'),status=document.getElementById('fixedStatus');if(controls.disabled)return;
   const data=new FormData(form),customerName=data.get('name').trim(),customerEmail=data.get('email').trim();if(!customerName){status.textContent=t('Please enter your name.','請輸入姓名。');return;}
   controls.disabled=true;status.textContent=t('Preparing your payment link…','正在準備付款連結…');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),45000);
   const api=['localhost','127.0.0.1'].includes(location.hostname)?document.querySelector('meta[name=checkout-api]')?.content||'http://127.0.0.1:8884':'https://calculator-oofl.onrender.com';
   try{const response=await fetch(api+'/create-payment-link',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({productId:p.id,collection:'silver',metal:'silver',quantity:1,paymentPercentage:100,customerName,customerEmail})});const result=await response.json();if(!response.ok||result.success!==true)throw Error('Unconfirmed');form.hidden=true;const success=document.createElement('p');success.setAttribute('role','status');success.textContent=t('Your payment link has been sent to '+customerEmail+'. Check your inbox and spam folder.','付款連結已發送至 '+customerEmail+'。請查看收件箱及垃圾郵件。');host.append(success);}catch{status.textContent=t('We could not confirm the payment link. Check your email before trying again, or contact us for help.','未能確認付款連結。再次嘗試前請先查看電郵，或聯絡我們。');}finally{clearTimeout(timeout);controls.disabled=false;}
  });
 }
 const sticky=document.createElement('a');sticky.href='#order';sticky.className='sticky-order';sticky.textContent=p.mode==='enquiry'?t('Book appointment ↓','預約諮詢 ↓'):t('Customise & order ↓','訂製及訂購 ↓');if(p.mode==='silver')sticky.textContent=t('Order this piece ↓','訂購此作品 ↓');document.body.append(sticky);
 new IntersectionObserver(entries=>{sticky.hidden=entries[0].isIntersecting;},{threshold:0}).observe(document.getElementById('order'));
})();
